### ISSUE TITLE
Idiomatic go practices

### ISSUE THREAD

**Issue by l50** [antman1p/gomythic#1]
I've got a couple of suggestions that are more idiomatic when it comes to go. Do you want a PR?

**Comment by l50** [comment]
You may want to rename the package and repo to something closer to `gomythic`. Underscores can cause some funkiness in the language and are typically reserved for tests.

**Comment by antman1p** [comment]
Changed name to `gomythic` in [f9c8ca0eac4182e1907fad9a19767aa67c6add4f](https://github.com/antman1p/gomythic/commit/f9c8ca0eac4182e1907fad9a19767aa67c6add4f)
